version: "3.8"
services:
  nodejs:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend/nodejs
  react:
    build:
      context: ./frontend/react-song-maker
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
     - ./frontend/react-song-maker:/frontend/react
    environment:
     - CHOKIDAR_USEPOLLING=true
  dotnet:
    build:
      context: ./auth-dotnet/auth-module
      dockerfile: Dockerfile.dev
    ports:
      - "5097:5097"
    volumes:
      - ./auth-dotnet/auth-module:/backend/dotnet

